language: python
python:
- 3.6
virtualenv:
  system_site_packages: true
install:
- pip install -r requirements.txt
script:
- pelican -d
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id:
    secure: "iZI/3rmYYQWfFMhRr3XCboUmu0E43CES3o6kWXq1qVu7QyJHfllUNw+OJ6rT0ErdwobnvwpLbTJ+E3GcWbQrjzagX+VwsHYvLr2msgLUul7gajv+aw99NP1T+RcLhO1ogv91tRfMQ72Rk0ZvrRHnooqNHmg5xKCCjwIET3R8QlJ+oOElWA6AIWDQINg0fu723IcJ644hVStoRg+KJnmpas5N245XCObcurxKqab0m+VeJ2ZVM1M/tU+CN+ynqQWjmF97AIz1+/FmX+1scAox4OWhKwXepz4G+qCi+IAIpY5yx6ANJAhyCHRI7YNEldhFa2JuOOzn6EFqRxokBPQmTIT4C5IYl8FRgzi1PbjHTVjC6oYOpU+UICSYqjRYj1zL//C26iqEHF0kVEuTLeRge+YUspxqZhUo1LO975OfX86R/oAhRDfoF3iHSvdycvRn4uAsNQUJ7bNhEu0VQDAtrauYT2TRt3YsKPKLhDaqn0wiOS1Aw9Ue7bnwNGc9jy7jlrFxJ5bl4Ytp4Fj41WHw51VYB0epgsjdE9RbNzuSSpRvY0VFRqXgVHyyoU81y8Mlq9bdghPXrhU809fnVKz+TOYNzVbhkRkx/7gkTySKRA4RK01JWBDD93e722gBhOMCX9cZxcf9zMorQMXGu3qToPcUSsHcDZrUWQ9PosdPvKk="
  secret_access_key:
    secure: JPhsJXRHXK35yHqN7zK0T4tQwfLD16zKYgO/6xBvAkg5YH4Z5ASCJfd4TbJ+4Y6L7ZwNgAGg5c+fK1O+5xMCWgavmJvn2IzWZjL61Z1mgSglk7SdwYcjD0YfACb4z+MSLa5bKYLm11GxHJ7sEdHHawVJFvRqrES9z+b5He27WnzQnS9jL1a6fmeBlKzQhBjz8NRWm1YnFqUyfj3X1hQHLNMYHkWG4+mEM5+BYbX44lrducYdFBW4XYnNsSTD0br7e2SJOC4oknrjm7E9N5DR28xPJLQvakkDfQKTaJeWpx71ETFRVlrID47PYcqexbiplmQdqBWX0AerdiIBa4ITYqZaAOq8q8y2USQt+T6oLCeaLzPB7dXGx7AdIdkBT+MditgzVd0W7mtA7fRjwZDvJ1hCW6VTKqV0TSZcdCKlpA1IXgR/CDXicYxdDnkcDGosk9/DXOCVq68ziTX8oxcpcCbxAj6Frg5QPDPMOf4UbyAxxwIVkqdgOcLsbjM3hn4fCABhMGKJmd+X7khjUrEzw/pBYB+cdDGRlPjz75xpM8UbT44Nc91eoyw1HMGxk9Y6hrKQdEP5401TgvTjbgZKKOGMfPgdsXrptMmermYpRicmnqcBdqtaLIjFyKe6rrgjRfDabQSs6rxgwBp5E3Pf57kOPKuUoxdYx3C3Nj4I3xM=
  bucket:
    secure: "TMgydKi6ZVku4riAb0xnwtoAG8jmerxSQItXkMBrltOLrjnOQ392Tn/pcFP6dAlcOolxWwoZJTg0dRfNjjBBn1gFd8/JnKV3uoN3R3EfumcEGvSDIMzMQShs+ZKf6GZlLNLFmSGlH9H5fddE2OZYdXyQkuHnG3XlwM1jIlyIFduXNAPPCNeF6PuAb+ecXC3aeBhYODaP57C+XwMdt2+KLRpQJMGTWNPf9RRb8RYvD0S0TZEgVx4QTLjAu8xlV9UXMn9oS+L82zkF4OmaDx3fMRgQLkAA3e4l/DYq8E/tTlOiY9nnt/kfaAsNKdwxbRqpmK+SEVASHNzHfSbHw6jFzSaPOnk7WTEPvTfGUFoO7YKyZp3Ye0Euk5Zkv8tk3ZwN+/TkLyeBRPQ2xLTClskVcEC0BZHTsNhWpuSrV4MJqiyTCuTkFGM/JqmlSNL3R96R8atm/ClFH7PhiOeXoKapxRpM3kloKhS7sUu2yKL4A3He6t3MKRDcRHlsR/yxXgRDpMEl8bJJVVcEvEtbbymeKrmqR/6biMJ/GEvedb8LaN53VQ9PMfv2CoGvyOrFW6GAPNwOeiyUmOKoiKake6GMlg+Rjlusq/bhFlhhNYRrWvnFCZ6bOwhSQTXsHKFhc3hvr7NWKydwUIXXsmVa26LxZwOPBHfe24VboTO4H94qi3I="
  local-dir: output
  acl: private
  on:
    repo: newmaniese/gpmomsclub.com
